version: '3.1'

services:
  db:
    container_name: honeydb
    image: postgres:14.4
    restart: always
    environment:
      POSTGRES_DB: honeydb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass123
    ports:
      - "5432:5432"